### ISSUE TITLE
Consider always sending Server Identifier

### ISSUE THREAD

**Issue by titanous** [nextdhcp/nextdhcp#12]
Follow-up to #11. [RFC 2131](https://tools.ietf.org/html/rfc2131) requires the server identifier option. Any reason it shouldn't be moved to the core packet handling code [here](https://github.com/nextdhcp/nextdhcp/blob/4ad05bd4bddc477eff2287a80b8cb466e14182c6/core/dhcpserver/server.go#L132)?

**Comment by ppacher** [comment]
I initially wanted to have all those functionality as plugins but since RFC 2131 requires the server identifier anyway I guess we can/should move that to the server core
