### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by gaby** [nextdhcp/nextdhcp#26]
Is this project still maintained? There hasnt been any releases in over a year.

**Comment by gaby** [comment]
> > Thanks for the update! I also noticed the website is down, and the domain name expired.
> 
> Yeah I already know that. My server is still happily serving the website but I just forgot to renew the domain name. I put it on my TODO and will take care of that once I'm back from my current trip. So expect an update in 1-2 weeks.
> 
> > If you ever need someone to takeover the project/group let me know, I got plenty of free time.
> 
> Thank you very much for your effort and suggestion here! I will definitely keep that in mind!
> 
> > In the meantime I just submitted a very basic PR to take care of some basic Github Workflow.
> 
> Awesome! Merged! :)

Once again, thanks for the update! Looking forward to seeing the website back live.

**Comment by gaby** [comment]
@ppacher Any updates on this?

**Comment by ppacher** [comment]
Hi @gaby 

thanks for pinging me here. Unfortunately not, I just don't have much time for that project and need to consider archiving this one. Are you interested in taking over maintenance?

**Comment by gaby** [comment]
@ppacher Yes, I can takeover the Project/Org. I already have some ideas of stuff to start working on (Migrating CI from Travis to Github, adding Docker support, Github Pagesbto host the website, etc).

**Comment by gaby** [comment]
@ppacher Let me know if you need anything from my side. I plan on getting the domain name again to host the documentation.

**Comment by ppacher** [comment]
Hi @gaby, I invited you to the nextdhcp organization. Once you accepted I'll grant you repository access and push permissions. I still like to keep the admin permission for now as I'm still not willing to let the project move away from me completely - it's still running as the DHCP server on multiple sites I manage :D and I would like to keep/start contributing again once I find some more time for that.

Once you have push/repository permissions feel free to start working and contributing! You can always ping me for Pull Request reviews as this is something I can more likely find some time for. This will also help me to keep up to date with changes you're planning to do :)

Other than that, thanks for pinging me again and for your effort to bring the project back to life :)

**Comment by gaby** [comment]
@ppacher Thanks for getting back to me. I just accepted the invite to the organization. Sounds good to me, looking forward to doing some contributions 👍🏻

**Comment by gaby** [comment]
@ppacher Haha! Yes, I can now see the other project tabs. Thanks for the quick response!
