### ISSUE TITLE
Unable to download Docker Image

### ISSUE THREAD

**Issue by gaby** [nextdhcp/nextdhcp#57]
@ppacher Seems like packages are made Private by default, can you make the image package public at the Organization level? I'm unable to change that setting.

Info here: https://github.community/t/how-to-make-gcr-organization-image-public/130492/3

**Comment by gaby** [comment]
@mcmar We can track the issue here

**Comment by ppacher** [comment]
Hi, I just changed the visibility to public. It should work now.
@gaby , you now also an org-admin so you guys don't need to wait for me the next time ;)

**Comment by gaby** [comment]
Thank you!
